In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('spotify-tracks.csv')
df.sample(5)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
43428,43428,6qYkNJmU5w4byWrqrXvDjE,Juninho Black,Temperou,Temperou,28,209826,False,0.841,0.3470,...,-9.110,1,0.0362,0.921,0.000744,0.1130,0.460,115.005,4,groove
102051,102051,6ymoA9aCgqTyoQLIeR7vCX,Taba Chake,Bombay Dreams,Shaayad,52,208000,False,0.606,0.4740,...,-8.498,1,0.0308,0.671,0.000009,0.1140,0.430,94.967,4,songwriter
113968,113968,4yoH9qzZQk1q7tQEiy4v4Y,Lucas Cervetti,Ámbar,Suspiro,21,89274,False,0.581,0.0618,...,-23.637,1,0.0460,0.981,0.952000,0.1010,0.402,65.978,4,world-music
95211,95211,6nxop4edP4uHU25CnWqqv0,Maelo Ruiz,Uniquehits,Te Amo,34,260773,False,0.764,0.6890,...,-9.630,1,0.0349,0.357,0.000204,0.0711,0.930,94.127,4,salsa
62334,62334,4T6HLdP6OcAtqC6tGnQelG,Michael Bublé,Call Me Irresponsible,Everything,71,212373,False,0.686,0.6880,...,-4.981,0,0.0254,0.390,0.000001,0.0924,0.493,123.125,4,j-pop

In [39]:
df.isna().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [40]:
df[df['album_name'].isna()]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,...,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [41]:
df.dropna(inplace=True)

In [42]:
df = df.iloc[:50000, :7]

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df.drop_duplicates(subset="track_id",inplace=True)

In [45]:
df

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853
...,...,...,...,...,...,...,...
49991,49991,2GIN5jc5IDdoVujHhC5NDo,Radical Redemption;N-Vitral,The Road To Redemption,Hover Through Hell,19,136000
49992,49992,6E0cm1PEAj4i851YTLsCaH,Adaro;Aftershock;Ava Silver,The Now And Then,The Now And Then - Extended Mix,19,294971
49995,49995,2DWNZunMWTsEoox83agzO2,Noisecontrollers;Bass Modulators,All Around,Faster N Further - Bass Modulators Remix,19,219871
49998,49998,2DgNGXMJ92AHIaBWYXI7XW,Brennan Heart,Evolution Of Style,F.I.F.O. (Outbreak Remix) - Edit,19,185600
49999,49999,4W26Z7WlOdxPYgu1mJxcD7,Jebroer;Paul Elstak,Kind Van De Duivel Vol. 2 - De Grootste Hardst...,Kind Eines Teufels,20,203079

In [46]:
df.to_csv("spotify-clean.csv")