In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('spotify-tracks.csv')
df.sample(5)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
60131,60131,1zc3ejK8IsDDbUZnDU1hDD,Spice,Emancipated,CROP TOP,40,127660,True,0.890,0.794,...,-6.769,1,0.2030,0.13400,0.000128,0.1330,0.552,102.110,4,j-dance
40928,40928,2bgb0Mohm0BFfbWQqiHxTb,J Neto,A Harpa Cristã (Interpretada por J Neto),A Ovelha Perdida,37,272277,False,0.414,0.241,...,-8.760,1,0.0350,0.88400,0.000000,0.1030,0.241,147.548,3,gospel
77380,77380,61XyXIWZFWh2zdRBAqVrrE,Sorriso Maroto,A.M.A (Ao Vivo),Sinal Vital - Ao Vivo,46,239690,False,0.581,0.707,...,-8.611,1,0.0393,0.73100,0.000004,0.9620,0.423,147.963,4,pagode
8921,8921,2Qj1FilGsXITZbFVmVeoLy,Freddie King,Getting Ready... (World),I'm Tore Down,54,253333,False,0.640,0.496,...,-11.124,1,0.0413,0.61600,0.000046,0.1830,0.954,116.632,4,blues
51725,51725,3WFAdUVTAuLeTMApMwGgvr,Machine Gun Kelly,Rock & Halloween,born with horns,4,147943,False,0.569,0.919,...,-5.378,1,0.1350,0.00089,0.000094,0.0524,0.256,95.073,4,hip-hop

In [16]:
df.isna().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [17]:
df[df['album_name'].isna()]

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,...,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [18]:
df.dropna(inplace=True)

In [19]:
df = df.iloc[:50000, :7]

In [20]:
df

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853
...,...,...,...,...,...,...,...
49995,49995,2DWNZunMWTsEoox83agzO2,Noisecontrollers;Bass Modulators,All Around,Faster N Further - Bass Modulators Remix,19,219871
49996,49996,5FbRok5VvNvgKFsockjSd7,The Prophet,The Hardcore Archive Part 2 (1995 - 1996),I Can't Stand It (4 Minute Mix) - Extended Mix,9,240350
49997,49997,01pX5frQUf9ioZQQJjGNxU,The Prophet,The Hardcore Archive Part 3 (1997),Nonono (Original Mix) - Extended Mix,0,346429
49998,49998,2DgNGXMJ92AHIaBWYXI7XW,Brennan Heart,Evolution Of Style,F.I.F.O. (Outbreak Remix) - Edit,19,185600
49999,49999,4W26Z7WlOdxPYgu1mJxcD7,Jebroer;Paul Elstak,Kind Van De Duivel Vol. 2 - De Grootste Hardst...,Kind Eines Teufels,20,203079

In [24]:
df.to_csv("spotify-clean.csv")