In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('../spotify-tracks.csv')
df.sample(5)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
71529,71529,3UygY7qW2cvG9Llkay6i1i,Evanescence,Fallen,Going Under,73,214946,False,0.370,0.858,...,-4.885,0,0.0545,0.00815,0.000021,0.2290,0.464,175.077,4,metal
96267,96267,249w6QiDEGJ4NqRpb02qoS,Ivete Sangalo;Pablo,Duetos 2,Vingança Do Amor,43,178200,False,0.568,0.730,...,-5.136,1,0.0375,0.20500,0.000000,0.3400,0.530,132.076,4,samba
83936,83936,6HnC8UJ9WqKUwx3dcha5Md,Mat Zo;OLAN;Fred Falke,Journey To ABGT500 pt.2,Colours (ABGT499D3) - Fred Falke Remix,38,202622,False,0.647,0.839,...,-6.864,0,0.0395,0.00005,0.499000,0.2020,0.191,122.040,4,progressive-house
98251,98251,3Rf5q1Ua1Dx031OsCE1XRQ,Mena Massoud,Aladdin (Original Motion Picture Soundtrack),One Jump Ahead (Reprise),47,60009,False,0.314,0.103,...,-16.886,1,0.0368,0.86700,0.004620,0.0973,0.134,48.991,4,show-tunes
36229,36229,4XANZ0xRF0vGRso3vJZVrF,Lonely in the Rain;Leo Stannard,Drifting,Drifting,60,206646,False,0.692,0.481,...,-9.084,1,0.0585,0.13700,0.000000,0.1500,0.367,115.007,4,french

## EXPLORANDO LOS DATOS

    Con esta función estaremos calculando que valores son nulos de cada columna.

In [17]:
df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [18]:
df.drop(columns="Unnamed: 0", inplace=True)

In [19]:
df.isna().sum()

track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

Después de utilizar la funcion `isna` vemos que existen 3 columnas con valor nulo, presuponemos que son la misma fila. Extraemos la fila:

In [20]:
df[df['album_name'].isna()]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

Tras confirmar que los tres valores nulos pertenecen a la misma fila, decidimos limpiarlos. A continuacion tratamos de ver si existen datos duplicados.

In [21]:
df.dropna(inplace=True)

In [22]:
df[df['album_name'].isna()]

Empty DataFrame
Columns: [track_id, artists, album_name, track_name, popularity, duration_ms, explicit, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, time_signature, track_genre]
Index: []

In [23]:
df = df.iloc[:50000, :6]

En el tratamiento inicial de los datos no detectamos duplicados, sin embargo tras trabajar con eld ataset nos dimos cuenta de los duplicados en el track_id.

In [24]:
df.duplicated().sum()

np.int64(5809)

In [25]:
df.duplicated(subset="track_id").sum()

np.int64(5810)

In [26]:
df.drop_duplicates(subset="track_id",inplace=True)

In [ ]:
df

,track_id,artists,album_name,track_name,popularity,duration_ms
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853
...,...,...,...,...,...,...
49991,2GIN5jc5IDdoVujHhC5NDo,Radical Redemption;N-Vitral,The Road To Redemption,Hover Through Hell,19,136000
49992,6E0cm1PEAj4i851YTLsCaH,Adaro;Aftershock;Ava Silver,The Now And Then,The Now And Then - Extended Mix,19,294971
49995,2DWNZunMWTsEoox83agzO2,Noisecontrollers;Bass Modulators,All Around,Faster N Further - Bass Modulators Remix,19,219871
49998,2DgNGXMJ92AHIaBWYXI7XW,Brennan Heart,Evolution Of Style,F.I.F.O. (Outbreak Remix) - Edit,19,185600
49999,4W26Z7WlOdxPYgu1mJxcD7,Jebroer;Paul Elstak,Kind Van De Duivel Vol. 2 - De Grootste Hardst...,Kind Eines Teufels,20,203079

In [28]:
df.to_csv("../spotify-clean.csv", index=False)