In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../spotify-tracks.csv')
df.sample(5)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
77703,77703,1so46EeQYGu2ol3Jwu3JLn,Grupo Malícia,Meus Sucessos # 4,Sentinela,43,223986,False,0.496,0.553,...,-12.638,1,0.0355,0.635000,0.000144,0.4310,0.940,159.209,4,pagode
71091,71091,7IMnJ5f7mRoGTtf8TPAILw,Volbeat,Halloween Party 2022,The Devil's Bleeding Crown,0,238653,False,0.321,0.909,...,-4.612,1,0.0410,0.000016,0.139000,0.0442,0.209,109.653,3,metal
49646,49646,0djKRTTzcqrjnEfBUsL9W3,Crypsis,In The Jungle,In The Jungle,21,230709,True,0.487,0.926,...,-2.670,0,0.0611,0.492000,0.000022,0.0362,0.212,154.992,4,hardstyle
94030,94030,0WSDEpEZZDffYfmK8Ssuxc,Louyah,6FEET,You,63,233196,False,0.808,0.266,...,-9.560,1,0.0326,0.818000,0.000011,0.0907,0.666,100.034,4,sad
20521,20521,6AjuU68Z5I6zzG03bs2MS2,Burna Boy;Ed Sheeran,Daily Pop Mix,For My Hand,0,159123,False,0.870,0.479,...,-7.779,1,0.1650,0.161000,0.000157,0.2090,0.717,104.059,4,dance

## EXPLORANDO LOS DATOS

    Con esta función estaremos calculando que valores son nulos de cada columna.

In [3]:
df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [4]:
df.drop(columns="Unnamed: 0", inplace=True)

In [5]:
df.isna().sum()

track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

Después de utilizar la funcion `isna` vemos que existen 3 columnas con valor nulo, presuponemos que son la misma fila. Extraemos la fila:

In [6]:
df[df['album_name'].isna()]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

Tras confirmar que los tres valores nulos pertenecen a la misma fila, decidimos limpiarlos. A continuacion tratamos de ver si existen datos duplicados.

In [7]:
df.dropna(inplace=True)

In [8]:
df[df['album_name'].isna()]

Empty DataFrame
Columns: [track_id, artists, album_name, track_name, popularity, duration_ms, explicit, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, time_signature, track_genre]
Index: []

In [9]:
df = df.iloc[:50000, :7]

En el tratamiento inicial de los datos no detectamos duplicados, sin embargo tras trabajar con eld ataset nos dimos cuenta de los duplicados en el track_id.

In [10]:
df.duplicated().sum()

np.int64(5809)

In [11]:
df.duplicated(subset="track_id").sum()

np.int64(5810)

In [12]:
df.drop_duplicates(subset="track_id",inplace=True)

In [13]:
df

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False
...,...,...,...,...,...,...,...
49991,2GIN5jc5IDdoVujHhC5NDo,Radical Redemption;N-Vitral,The Road To Redemption,Hover Through Hell,19,136000,True
49992,6E0cm1PEAj4i851YTLsCaH,Adaro;Aftershock;Ava Silver,The Now And Then,The Now And Then - Extended Mix,19,294971,False
49995,2DWNZunMWTsEoox83agzO2,Noisecontrollers;Bass Modulators,All Around,Faster N Further - Bass Modulators Remix,19,219871,False
49998,2DgNGXMJ92AHIaBWYXI7XW,Brennan Heart,Evolution Of Style,F.I.F.O. (Outbreak Remix) - Edit,19,185600,False
49999,4W26Z7WlOdxPYgu1mJxcD7,Jebroer;Paul Elstak,Kind Van De Duivel Vol. 2 - De Grootste Hardst...,Kind Eines Teufels,20,203079,False

In [14]:
df.to_csv("../spotify-clean.csv", index=False)